include:
  - ../networks.yml
  - ../pgvector-17.yml
  - ../redis-7.yml
x-environment: &environment
  WEBAPP_URL: https://${APP_NAME}.${DAPPS_DOMAIN}
  NEXTAUTH_URL: https://${APP_NAME}.${DAPPS_DOMAIN}
  DATABASE_URL: "postgresql://${APP_NAME}:${DAPPS_DATABASE_PASSWORD}@pgvector:5432/${APP_NAME}?schema=public"
  NEXTAUTH_SECRET: ${DAPPS_KEY_HEX_32}
  ENCRYPTION_KEY: ${DAPPS_KEY_HEX_32}
  CRON_SECRET: ${DAPPS_KEY_HEX_32}
  EMAIL_VERIFICATION_DISABLED: 1
  PASSWORD_RESET_DISABLED: 1
  S3_ACCESS_KEY: ${DAPPS_S3_ACCESS_KEY_ID}
  S3_SECRET_KEY: ${DAPPS_S3_SECRET_ACCESS_KEY}
  S3_REGION: auto
  S3_BUCKET_NAME: ${CODECOV_S3_BUCKET}
  S3_ENDPOINT_URL: ${DAPPS_S3_HOST}
  S3_FORCE_PATH_STYLE: 0
  REDIS_URL: redis://redis:6379/1
services:
  formbricks:
    extends:
      file: ../common.yml
      service: main
    image: ghcr.io/formbricks/formbricks
    environment: *environment
    depends_on:
      - pgvector
      - redis
