include:
  - ../networks.yml
services:
  sonarr:
    extends:
      file: ../common.yml
      service: main
    image: ghcr.io/hotio/sonarr
    environment:
      TZ: ${DAPPS_TIMEZONE}
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
      - ../../apps-data/${APP_NAME}/data:/data
