include:
  - ../networks.yml
x-environment: &environment
  PUID: ${DAPPS_UID}
  PGID: ${DAPPS_GID}
  TZ: ${DAPPS_TIMEZONE}
services:
  sonarr:
    extends:
      file: ../common.yml
      service: main
    image: ghcr.io/hotio/sonarr
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
      - ${QBITTORRENT_DOWNLOADS_PATH}:/downloads
      - ${JELLYFIN_SHOWS_PATH}:/shows
