include:
  - ../networks.yml
x-environment: &environment
  PUID: ${APPS_UID}
  PGID: ${APPS_GID}
  TZ: ${APPS_TIMEZONE}
services:
  sonarr:
    extends:
      file: ../common.yml
      service: main
    expose:
      - 8989
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=8989"
    image: ghcr.io/hotio/sonarr
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${JELLYFIN_SHOWS_PATH}:/shows
