include:
  - ../networks.yml
  - ../redis.yml
services:
  browserless: # marked
    image: browserless/chrome # marked
    restart: unless-stopped # marked
    ulimits: # marked
      core: # marked
        hard: 0 # marked
        soft: 0 # marked
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/pressure"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - internal
  rsshub:
    # two ways to enable puppeteer:
    # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled
    # * (consumes more disk space and memory) leave everything unchanged
    extends:
      file: ../common.yml
      service: main
    image: diygod/rsshub
    environment:
      - NODE_ENV=production
      - CACHE_TYPE=redis
      - REDIS_URL=redis://redis:6379/
      - PUPPETEER_WS_ENDPOINT=ws://browserless:3000 # marked
      - ACCESS_KEY=${RSSHUB_ACCESS_KEY}
      - TWITTER_AUTH_TOKEN=${RSSHUB_TWITTER_AUTH_TOKEN}
      - YOUTUBE_KEY=${RSSHUB_YOUTUBE_KEY}
      - POSTGRES_PASSWORD=postgres
      - ${RSSHUB_EMAIL_CONFIG}
      - ${RSSHUB_MEDIUM_CONFIG}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${APP_PORT}/healthz?key=${RSSHUB_ACCESS_KEY}",
        ]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
    depends_on:
      - redis
      - browserless # marked
