include:
  - ../redis.yml
services:
  browserless: # marked
    image: browserless/chrome # marked
    restart: unless-stopped # marked
    ulimits: # marked
      core: # marked
        hard: 0 # marked
        soft: 0 # marked
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/pressure" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - internal
  rsshub:
    # two ways to enable puppeteer:
    # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled
    # * (consumes more disk space and memory) leave everything unchanged
    image: diygod/rsshub
    restart: unless-stopped
    expose:
      - 1200
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: "redis://redis:6379/"
      PUPPETEER_WS_ENDPOINT: "ws://browserless:3000" # marked
      ACCESS_KEY: ${RSSHUB_ACCESS_KEY}
      TWITTER_AUTH_TOKEN: ${RSSHUB_TWITTER_AUTH_TOKEN}
      YOUTUBE_KEY: ${RSSHUB_YOUTUBE_KEY}
      MEDIUM_COOKIE_ineedjet: ${RSSHUB_MEDIUM_COOKIE_INEEDJET}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1200/healthz?key=${RSSHUB_ACCESS_KEY}" ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - redis
      - browserless # marked
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${DAPPS_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=acmeHttpChallengeResolver"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=1200"
    networks:
      - internal
      - traefik
networks:
  internal:
  traefik:
    external: true
