include:
  - ../networks.yml
x-environment: &environment
  PUID: ${APPS_UID}
  PGID: ${APPS_GID}
  TZ: ${APPS_TIMEZONE}
services:
  grocy:
    extends:
      file: ../common.yml
      service: main
    expose:
      - 80
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
    image: lscr.io/linuxserver/grocy
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
