services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    volumes:
      - ./data:/datastore
    expose:
      - 5000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.${DOMAIN}`)"
      - "traefik.http.routers.${NAME}.tls.certresolver=acmeHttpChallengeResolver"
      - "traefik.http.services.${NAME}.loadbalancer.server.port=5000"
    networks:
      - traefik
networks:
  traefik:
    external: true
