include:
  - ../networks.yml
services:
  sshd:
    image: testcontainers/sshd:1.2.0
    volumes:
      - ~/.ssh/authorized_keys:/root/.ssh/authorized_keys
    ports:
      - 10022:22
    restart: unless-stopped
    networks:
      - databases
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 22 || exit 1"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
