include:
  - ../networks.yml
services:
  homarr:
    extends:
      file: ../common.yml
      service: main
    image: ghcr.io/ajnart/homarr
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../apps-data/${APP_NAME}/config:/app/data/configs
      - ../../apps-data/${APP_NAME}/icons:/app/public/icons
      - ../../apps-data/${APP_NAME}/data:/data
