services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.`${NAME}`.rule=Host(`${NAME}.${DOMAIN}`)"
      - "traefik.http.routers.`${NAME}`.tls.certresolver=acmeHttpChallengeResolver"
    networks:
      - traefik
networks:
  traefik:
    external: true
