services:
    postgres:
        image: postgres:latest
        container_name: postgres
        hostname: postgres
        volumes:
            - ./postgresql:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: metabase
            POSTGRES_DB: metabaseappdb
            POSTGRES_PASSWORD: mysecretpassword
        networks:
            - internal
    metabase:
        image: metabase/metabase:latest
        container_name: metabase
        hostname: metabase
        volumes:
            - /dev/urandom:/dev/random:ro
        expose:
            - 3000
        environment:
            MB_DB_TYPE: postgres
            MB_DB_DBNAME: metabaseappdb
            MB_DB_PORT: 5432
            MB_DB_USER: metabase
            MB_DB_PASS: mysecretpassword
            MB_DB_HOST: postgres
        healthcheck:
            test: curl --fail -I http://localhost:3000/api/health || exit 1
            interval: 15s
            timeout: 5s
            retries: 5
        networks:
            - internal
            - traefik
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.${DOMAIN}`)"
            - "traefik.http.routers.${NAME}.tls.certresolver=acmeHttpChallengeResolver"
            - "traefik.http.services.${NAME}.loadbalancer.server.port=3000"
networks:
    internal:
    traefik:
        external: true
