services:
  mongo:
    image: "mongo:latest"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongodb:/data/db
    networks:
      - internal
  growthbook:
    image: "growthbook/growthbook:latest"
    expose:
      - 3000
      - 3100
    depends_on:
      - mongo
    environment:
      - APP_ORIGIN=https://${NAME}.${DOMAIN}
      - API_HOST=https://${NAME}-api.${DOMAIN}
      - MONGODB_URI=mongodb://root:password@mongo:27017/growthbook?authSource=admin
      - JWT_SECRET=${SECRET_KEY}
    volumes:
      - ./storage:/usr/local/src/app/packages/back-end/uploads
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.${DOMAIN}`)"
      - "traefik.http.routers.${NAME}.tls.certresolver=acmeHttpChallengeResolver"
      - "traefik.http.routers.${NAME}.service=${NAME}"
      - "traefik.http.services.${NAME}.loadbalancer.server.port=3000"
      - "traefik.http.routers.${NAME}-api.rule=Host(`${NAME}-api.${DOMAIN}`)"
      - "traefik.http.routers.${NAME}-api.tls.certresolver=acmeHttpChallengeResolver"
      - "traefik.http.routers.${NAME}-api.service=${NAME}-api"
      - "traefik.http.services.${NAME}-api.loadbalancer.server.port=3100"
networks:
  internal:
  traefik:
    external: true
