services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    environment:
      - COLLECTOR_CRON_SCHEDULE='0 */1 * * *'
    expose:
      - ${APP_PORT} # webapp
      - "8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ../../apps-data/${APP_NAME}/config:/opt/scrutiny/config
      - ../../apps-data/${APP_NAME}/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/nvme0"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${DAPPS_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=${DAPPS_CERTIFICATE_RESOLVER}"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"
    networks:
      - traefik
networks:
  traefik:
    external: true
