include:
  - ../networks.yml
services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    extends:
      file: ../common.yml
      service: main
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    environment:
      COLLECTOR_CRON_SCHEDULE: '0 */3 * * *'
      SCRUTINY_NOTIFY_URLS: >
        ${DAPPS_SHOUTRRR_TELEGRAM_NOTIFICATION_URL}
    volumes:
      - /run/udev:/run/udev:ro
      - ../../apps-data/${APP_NAME}/config:/opt/scrutiny/config
      - ../../apps-data/${APP_NAME}/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/nvme0"
      - "/dev/sda"
