include:
  - ../networks.yml
  - ../postgres-17.yml
x-environment: &environment
  SECRET_KEY: ${APPS_KEY_HEX_64}
  CREATE_SUPERUSER: ${APPS_ADMIN_MAIL}:${APPS_ADMIN_MAIL}
  PORT: 8000
  DATABASE_URL: postgresql://${APP_NAME}:${APPS_DATABASE_PASSWORD}@postgres:5432/${APP_NAME}
  BEHIND_HTTPS_PROXY: true
  BASE_URL: https://${APP_NAME}.${APPS_DOMAIN}
services:
  bugsink:
    image: bugsink/bugsink
    extends:
      file: ../common.yml
      service: main
    depends_on:
      - postgres
    environment: *environment
