include:
  - ../networks.yml
  - ../postgres.yml
services:
  bugsink:
    image: bugsink/bugsink
    extends:
      file: ../common.yml
      service: main
    depends_on:
      - postgres
    environment:
      SECRET_KEY: ${DAPPS_KEY_HEX_64}
      CREATE_SUPERUSER: ${DAPPS_ADMIN_MAIL}:${DAPPS_ADMIN_MAIL}
      PORT: 8000
      DATABASE_URL: postgresql://${APP_NAME}:${DAPPS_DATABASE_PASSWORD}@postgres:5432/${APP_NAME}
      BEHIND_HTTPS_PROXY: "true"
      BASE_URL: https://${APP_NAME}.${DAPPS_DOMAIN}
