#!/bin/bash
validate_app_name() {
  local app

  app="$1"
  if [[ ! "$app" =~ ^[a-z][a-z0-9-]*$ ]]; then
    echo "Invalid app name: $app" >&2
    return 1
  fi
}

app_env_prefix() {
  local app="$1"

  validate_app_name "$app" || return 1
  echo "$app" | tr '[:lower:]-' '[:upper:]_'
}

parse_apps() {
  local raw="${1:-}"
  local app
  local parsed_apps

  apps=()
  raw="${raw//$'\n'/,}"

  IFS=',' read -r -a parsed_apps <<< "$raw"
  for app in "${parsed_apps[@]}"; do
    app="${app#"${app%%[![:space:]]*}"}"
    app="${app%"${app##*[![:space:]]}"}"

    if [[ -z "$app" ]]; then
      echo "Invalid APPS value: empty app name in '$raw'" >&2
      return 1
    fi
    validate_app_name "$app" || return 1

    apps+=("$app")
  done

  if [[ ${#apps[@]} -eq 0 ]]; then
    echo "APPS must contain at least one app name" >&2
    return 1
  fi
}

require_app_compose() {
  local app="$1"

  validate_app_name "$app" || return 1

  if [[ ! -f "./apps/${app}/docker-compose.yml" ]]; then
    echo "Missing compose file for app: ./apps/${app}/docker-compose.yml" >&2
    return 1
  fi
}

generate_env() {
  local app="$1"
  local prefix
  local output="./apps/${app}/.env"

  require_app_compose "$app"
  prefix="$(app_env_prefix "$app")"

  {
    cat .env
    echo "APP_NAME=${app}"
  } | awk -v prefix="${prefix}" '
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*$/ { next }
    /=/ {
      key = substr($0, 1, index($0, "=") - 1)
      if (key != "APP_NAME" && key !~ /^APPS_/ && index(key, prefix "_") != 1) { next }
      vals[key] = $0
      if (!(key in seen)) { order[++n] = key; seen[key] = 1 }
    }
    END { for (i = 1; i <= n; i++) print vals[order[i]] }
  ' | { echo "# Auto-generated by up.sh — do not edit. Use ./up.sh in project root to regenerate."; cat; } > "$output"
}
