#!/bin/bash
generate_env() {
  local app="$1"
  local output="./apps/${app}/.env"
  {
    cat .env
    echo "APP_NAME=${app}"
  } | awk '
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*$/ { next }
    /=\(/ { next }
    /=/ {
      key = substr($0, 1, index($0, "=") - 1)
      vals[key] = $0
      if (!(key in seen)) { order[++n] = key; seen[key] = 1 }
    }
    END { for (i = 1; i <= n; i++) print vals[order[i]] }
  ' | { echo "# Auto-generated by up.sh — do not edit. Use ./up.sh in project root to regenerate."; cat; } > "$output"
}
