services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      # default WATCHTOWER_NOTIFICATIONS_LEVEL: "info"
      WATCHTOWER_NOTIFICATIONS_LEVEL: "warn"
      WATCHTOWER_SCHEDULE: "30 30 23 * * *"
      TZ: ${DAPPS_TIMEZONE}
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "true"
      WATCHTOWER_ROLLING_RESTART: "true"
      WATCHTOWER_NOTIFICATIONS_HOSTNAME: ${DAPPS_HOST_NAME}
      WATCHTOWER_NOTIFICATION_TITLE_TAG: '🗼'
      WATCHTOWER_NOTIFICATION_URL: >
        ${DAPPS_SHOUTRRR_TELEGRAM_NOTIFICATION_URL}
      # Не показывать Fresh контейнеры?
      WATCHTOWER_NOTIFICATION_TEMPLATE: |
        {{- if .Report -}}
          {{- with .Report -}}
            {{- range .Updated}}
        - {{.Name}} ({{.ImageName}}): Updated
            {{- end -}}
            {{- range .Skipped}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
            {{- range .Failed}}
        - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
            {{- end -}}
          {{- end -}}
        {{- else -}}
          {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
        {{- end -}}
      # WATCHTOWER_NOTIFICATION_TEMPLATE: |
      #  {{- if .Report -}}
      #    {{- with .Report -}}
      #  {{len .Scanned}} Scanned, {{len .Updated}} Updated, {{len .Failed}} Failed
      #        {{- range .Updated}}
      #  - {{.Name}} ({{.ImageName}}): {{.CurrentImageID.ShortID}} updated to {{.LatestImageID.ShortID}}
      #        {{- end -}}
      #        {{- range .Fresh}}
      #  - {{.Name}} ({{.ImageName}}): {{.State}}
      #      {{- end -}}
      #      {{- range .Skipped}}
      #  - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
      #      {{- end -}}
      #      {{- range .Failed}}
      #  - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
      #      {{- end -}}
      #    {{- end -}}
      #  {{- else -}}
      #    {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
      #  {{- end -}}
