x-environment: &environment
  WATCHTOWER_LABEL_ENABLE: true
  WATCHTOWER_NOTIFICATION_REPORT: true
  WATCHTOWER_NOTIFICATIONS_LEVEL: warn
  WATCHTOWER_SCHEDULE: "30 30 23 * * *"
  TZ: ${APPS_TIMEZONE}
  WATCHTOWER_CLEANUP: true
  WATCHTOWER_NO_STARTUP_MESSAGE: true
  WATCHTOWER_ROLLING_RESTART: false
  WATCHTOWER_NOTIFICATIONS_HOSTNAME: ${APPS_HOST_NAME}
  WATCHTOWER_NOTIFICATION_TITLE_TAG: "🗼"
  WATCHTOWER_NOTIFICATION_URL: "telegram://${APPS_TELEGRAM_TOKEN}@telegram?chats=${APPS_TELEGRAM_CHAT}&preview=false"
  WATCHTOWER_NOTIFICATION_TEMPLATE: |
    {{- if .Report -}}
      {{- with .Report -}}
        {{- range .Updated}}
    - {{.Name}} ({{.ImageName}}): Updated
        {{- end -}}
        {{- range .Skipped}}
    - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
        {{- end -}}
        {{- range .Failed}}
    - {{.Name}} ({{.ImageName}}): {{.State}}: {{.Error}}
        {{- end -}}
      {{- end -}}
    {{- else -}}
      {{range .Entries -}}{{.Message}}{{"\n"}}{{- end -}}
    {{- end -}}
services:
  watchtower:
    image: nickfedor/watchtower
    environment: *environment
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
