include:
  - ../networks.yml
  - ../postgres-17.yml
x-environment: &environment
  MB_DB_TYPE: postgres
  MB_DB_DBNAME: ${APP_NAME}
  MB_DB_PORT: 5432
  MB_DB_USER: ${APP_NAME}
  MB_DB_PASS: ${APPS_DATABASE_PASSWORD}
  MB_DB_HOST: postgres
services:
  metabase:
    extends:
      file: ../common.yml
      service: main
    image: metabase/metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    environment: *environment
    healthcheck:
      test: curl --fail -I http://localhost:${APP_PORT}/api/health || exit 1
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
