include:
  - ../postgres.yml
services:
  metabase:
    image: metabase/metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    expose:
      - ${APP_PORT}
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${APP_NAME}
      MB_DB_PORT: 5432
      MB_DB_USER: ${APP_NAME}
      MB_DB_PASS: ${DAPPS_DATABASE_PASSWORD}
      MB_DB_HOST: postgres
    healthcheck:
      test: curl --fail -I http://localhost:${APP_PORT}/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${DAPPS_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=${DAPPS_CERTIFICATE_RESOLVER}"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"
networks:
  internal:
  databases:
    external: true
  traefik:
    external: true
