services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    volumes:
      - ../../apps-data/${APP_NAME}/datastore:/datastore
    expose:
      - 5000
    restart: unless-stopped
    environment:
      - PLAYWRIGHT_DRIVER_URL=ws://sockpuppetbrowser:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${DAPPS_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=${DAPPS_CERTIFICATE_RESOLVER}"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=5000"
    depends_on:
      - sockpuppetbrowser
    networks:
      - internal
      - traefik
  # Sockpuppetbrowser is basically chrome wrapped in an API for allowing fast fetching of web-pages.
  # RECOMMENDED FOR FETCHING PAGES WITH CHROME
  sockpuppetbrowser:
    hostname: sockpuppetbrowser
    image: dgtlmoon/sockpuppetbrowser
    restart: unless-stopped
    environment:
        - SCREEN_WIDTH=1920
        - SCREEN_HEIGHT=1024
        - SCREEN_DEPTH=16
        - MAX_CONCURRENT_CHROME_PROCESSES=10
    networks:
      - internal
networks:
  internal:
  traefik:
    external: true
