include:
  - ../networks.yml
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    extends:
      file: ../common.yml
      service: main
    expose:
      - 5000
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=5000"
    volumes:
      - ../../apps-data/${APP_NAME}/datastore:/datastore
