include:
  - ../networks.yml
services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    extends:
      file: ../common.yml
      service: main
    volumes:
      - ../../apps-data/${APP_NAME}/datastore:/datastore
