include:
  - ../networks.yml
  - ../postgres-17.yml
  - ../redis-7.yml
x-environment: &environment
  AP_ENGINE_EXECUTABLE_PATH: dist/packages/engine/main.js
  AP_API_KEY: ${DAPPS_KEY_HEX_64}
  AP_ENCRYPTION_KEY: ${DAPPS_KEY_HEX_16}
  AP_JWT_SECRET: ${DAPPS_KEY_HEX_32}
  AP_ENVIRONMENT: prod
  AP_FRONTEND_URL: https://${APP_NAME}.${DAPPS_DOMAIN}
  AP_WEBHOOK_TIMEOUT_SECONDS: 30
  AP_TRIGGER_DEFAULT_POLL_INTERVAL: 5
  AP_POSTGRES_USERNAME: ${APP_NAME}
  AP_POSTGRES_PASSWORD: ${DAPPS_DATABASE_PASSWORD}
  AP_POSTGRES_DATABASE: ${APP_NAME}
  AP_POSTGRES_HOST: postgres
  AP_POSTGRES_PORT: 5432
  AP_EXECUTION_MODE: UNSANDBOXED
  AP_REDIS_HOST: redis
  AP_REDIS_PORT: 6379
  AP_FLOW_TIMEOUT_SECONDS: 600
  AP_TELEMETRY_ENABLED: true
  AP_TEMPLATES_SOURCE_URL: "https://cloud.activepieces.com/api/v1/flow-templates"
services:
  activepieces:
    image: ghcr.io/activepieces/activepieces
    extends:
      file: ../common.yml
      service: main
    ## Enable the following line if you already use AP_EXECUTION_MODE with SANDBOXED or old activepieces, checking the breaking change documentation for more info.
    ## privileged: true
    environment: *environment
    depends_on:
      - postgres
      - redis
    volumes:
      - ../../apps-data/${APP_NAME}/cache:/usr/src/app/cache
