include:
  - ../networks.yml
x-environment: &environment
  VPN_ENABLED: yes
  VPN_PROV: custom
  VPN_CLIENT: ${VPN_CLIENT}
  VPN_USER: ${VPN_USER}
  VPN_PASS: ${VPN_PASS}
  LAN_NETWORK: 172.16.0.0/12
  NAME_SERVERS: 1.1.1.1,8.8.8.8
  WEBUI_PORT: ${APP_PORT}
  UMASK: 002
  PUID: ${DAPPS_UID}
  PGID: ${DAPPS_GID}
services:
  arch-qbittorrentvpn:
    image: binhex/arch-qbittorrentvpn
    extends:
      file: ../common.yml
      service: main
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
      - ${DOWNLOADS_PATH}:/downloads
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    privileged: true
