include:
  - ../networks.yml
  - ../mysql-8.yml
x-environment: &environment
  ADMINMAIL: ${APPS_ADMIN_MAIL}
  ADMINPASS: ${APPS_ADMIN_DEFAULT_PASS}
  DATABASE_URL: mysql://${APP_NAME}:${APPS_DATABASE_PASSWORD}@mysql/${APP_NAME}
  TRUSTED_HOSTS: ${APP_NAME}.${APPS_DOMAIN}|localhost|127.0.0.1
  TRUSTED_PROXIES: 172.16.0.0/12,10.0.0.0/8
services:
  kimai:
    extends:
      file: ../common.yml
      service: main
    image: kimai/kimai2:apache
    volumes:
      - ../../apps-data/${APP_NAME}/data:/opt/kimai/var/data
      - ../../apps-data/${APP_NAME}/plugins:/opt/kimai/var/plugins
    environment: *environment
