x-environment: &environment
  DISK_SIZE: "16G"
services:
  virtual-dsm:
    image: vdsm/virtual-dsm
    environment: *environment
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ${APP_DATA}/storage:/storage
    stop_grace_period: 2m
