include:
  - ../networks.yml
  - ../postgres.yml
  - ../redis.yml
x-image: &image n8nio/n8n
x-environment: &environment
  DB_TYPE: postgresdb
  DB_POSTGRESDB_HOST: postgres
  DB_POSTGRESDB_PORT: 5432
  DB_POSTGRESDB_DATABASE: ${APP_NAME}
  DB_POSTGRESDB_USER: ${APP_NAME}
  DB_POSTGRESDB_PASSWORD: ${DAPPS_DATABASE_PASSWORD}
  EXECUTIONS_MODE: queue
  QUEUE_BULL_REDIS_HOST: redis
  QUEUE_HEALTH_CHECK_ACTIVE: true
  N8N_ENCRYPTION_KEY: ${DAPPS_KEY_HEX_32}
  GENERIC_TIMEZONE: ${DAPPS_TIMEZONE}
  N8N_HOST: ${APP_NAME}.${DAPPS_DOMAIN}
  N8N_PROTOCOL: https
  NODE_ENV: production
  WEBHOOK_URL: https://${APP_NAME}.${DAPPS_DOMAIN}/
x-volumes: &volumes
  - ../../apps-data/${APP_NAME}/data:/home/node/.n8n
  - ../../apps-data/${APP_NAME}/files:/files
services:
  n8n:
    extends:
      file: ../common.yml
      service: main
    environment: *environment
    volumes: *volumes
    image: *image
    depends_on:
      - initContainer
      - redis
      - postgres
  n8n-worker:
    extends:
      file: ../common.yml
      service: side
    environment: *environment
    volumes: *volumes
    command: worker
    depends_on:
      - n8n
      - redis
      - postgres
  initContainer:
    image: busybox
    command: [ 'sh', '-c', 'chown -R 1000:1000 /home/node/.n8n' ]
    volumes: *volumes
