services:
    rsshub:
        # two ways to enable puppeteer:
        # * comment out marked lines, then use this image instead: diygod/rsshub:chromium-bundled
        # * (consumes more disk space and memory) leave everything unchanged
        image: diygod/rsshub
        container_name: rsshub
        restart: unless-stopped
        ports:
            - "1200:1200"
        environment:
            NODE_ENV: production
            CACHE_TYPE: redis
            REDIS_URL: "redis://redis:6379/"
            PUPPETEER_WS_ENDPOINT: "ws://browserless:3000" # marked
            ACCESS_KEY: ${RSSHUB_ACCESS_KEY}
            TWITTER_USERNAME: ${RSSHUB_TWITTER_USERNAME}
            TWITTER_PASSWORD: ${RSSHUB_TWITTER_PASSWORD}
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:1200/healthz?key=${RSSHUB_ACCESS_KEY}" ]
            interval: 30s
            timeout: 10s
            retries: 3
        depends_on:
            - redis
            - browserless # marked
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.${DOMAIN}`)"
            - "traefik.http.routers.${NAME}.tls.certresolver=acmeHttpChallengeResolver"
        networks:
            - internal
            - traefik
    browserless: # marked
        image: browserless/chrome # marked
        restart: unless-stopped # marked
        ulimits: # marked
            core: # marked
                hard: 0 # marked
                soft: 0 # marked
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/pressure"]
            interval: 30s
            timeout: 10s
            retries: 3
        networks:
            - internal
    redis:
        image: redis:alpine
        restart: unless-stopped
        volumes:
            - ./redis:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 5s
        networks:
            - internal
networks:
    internal:
    traefik:
        external: true
