include:
  - ../networks.yml
services:
  flaresolverr:
    extends:
      file: ../common.yml
      service: main
    image: ghcr.io/flaresolverr/flaresolverr
    environment:
      LOG_LEVEL: info
      TZ: ${DAPPS_TIMEZONE}
