include:
  - ../networks.yml
x-environment: &environment
  LOG_LEVEL: info
  TZ: ${DAPPS_TIMEZONE}
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    extends:
      file: ../common.yml
      service: main
    environment: *environment
