include:
  - ../networks.yml
services:
  radarr:
    extends:
      file: ../common.yml
      service: main
    image: ghcr.io/hotio/radarr
    environment:
      TZ: ${DAPPS_TIMEZONE}
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
      - ../../apps-data/${APP_NAME}/data:/data
      - ${QBITTORRENT_DOWNLOADS_PATH}:/downloads
      - ${JELLYFIN_VIDEO_PATH}:/video
