include:
  - ../networks.yml
x-environment: &environment
  PUID: 1000
  PGID: 1000
  TZ: ${DAPPS_TIMEZONE}
services:
  radarr:
    image: ghcr.io/hotio/radarr
    extends:
      file: ../common.yml
      service: main
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
      - ${QBITTORRENT_DOWNLOADS_PATH}:/downloads
      - ${JELLYFIN_VIDEO_PATH}:/video
