include:
  - ../networks.yml
  - ../postgres.yml
x-image: &image ghcr.io/goauthentik/server:${APP_VERSION}
x-environment: &environment
  AUTHENTIK_BOOTSTRAP_PASSWORD: ${DAPPS_ADMIN_DEFAULT_PASS}
  AUTHENTIK_BOOTSTRAP_EMAIL: ${DAPPS_ADMIN_MAIL}
  AUTHENTIK_SECRET_KEY: ${DAPPS_KEY_HEX_64}
  AUTHENTIK_ERROR_REPORTING__ENABLED: false
  AUTHENTIK_POSTGRESQL__HOST: postgres
  AUTHENTIK_POSTGRESQL__NAME: ${APP_NAME}
  AUTHENTIK_POSTGRESQL__USER: ${APP_NAME}
  AUTHENTIK_POSTGRESQL__PASSWORD: ${DAPPS_DATABASE_PASSWORD}
x-volumes: &volumes
  - ../../apps-data/${APP_NAME}/media:/media
  - ../../apps-data/${APP_NAME}/templates:/templates
  - ../../apps-data/${APP_NAME}/certs:/certs
services:
  server:
    image: *image
    extends:
      file: ../common.yml
      service: main
    command: server
    environment: *environment
    volumes: *volumes
    depends_on:
      - postgres
  worker:
    image: *image
    extends:
      file: ../common.yml
      service: side
    command: worker
    environment: *environment
    volumes: *volumes
    depends_on:
      - postgres
