include:
  - ../networks.yml
services:
  metube:
    extends:
      file: ../common.yml
      service: main
    expose:
      - 8081
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=8081"
    image: ghcr.io/alexta69/metube
    volumes:
      - ${METUBE_DOWNLOADS_PATH}:/downloads
