include:
  - ../networks.yml
services:
  metube:
    extends:
      file: ../common.yml
      service: main
    image: ghcr.io/alexta69/metube
    volumes:
      - ${METUBE_DOWNLOADS_PATH}:/downloads
