include:
  - ../networks.yml
services:
  icloudpd:
    extends:
      file: ../common.yml
      service: main
    image: icloudpd/icloudpd
    command: >
      icloudpd
        --username "${ICLOUDPD_USERNAME}"
        --password-provider webui
        --mfa-provider webui
        --directory /data
        --cookie-directory /cookies
        --folder-structure none
        --set-exif-datetime
        --auto-delete
        --watch-with-interval 180
        --keep-unicode-in-filenames
        --album "${ICLOUDPD_ALBUM}"
    volumes:
      - ../../apps-data/${APP_NAME}/cookies:/cookies
      - ${ICLOUDPD_DATA_PATH}/data:/data
