services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    container_name: speedtest-tracker
    expose:
      - 80
      - 443
    environment:
      - PUID=1000
      - PGID=1000
      - APP_KEY=${ENCRYPTION_KEY}
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE='*/10 * * * *'
      - SPEEDTEST_SERVERS='55462,54504'
    volumes:
      - ./data:/config
      - ./keys:/config/keys
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.${DOMAIN}`)"
      - "traefik.http.routers.${NAME}.tls.certresolver=acmeHttpChallengeResolver"
      - "traefik.http.services.${NAME}.loadbalancer.server.port=80"
networks:
  traefik:
    external: true
