global:
  checkNewVersion: true
  sendAnonymousUsage: false
api:
  dashboard: true
providers:
  docker:
    exposedByDefault: false
log:
  level: INFO
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
certificatesResolvers:
  myresolver:
    acme:
      email: your_email@examdtfple.com
      storage: acme.json
      httpChallenge:
        entryPoint: web
