global:
  checkNewVersion: true
  sendAnonymousUsage: false
log:
  level: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
accesslog: {}
  # format: common # common, json, logfmt
  # filePath: /var/log/traefik/access.log
api:
  dashboard: true
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: false
  https:
    address: ":443"
providers:
  docker:
    # endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik
    watch: true
certificatesResolvers:
  acmeHttpChallengeResolver:
    acme:
      email: your_email@examdtfple.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
