include:
  - ../networks.yml
services:
  prowlarr:
    extends:
      file: ../common.yml
      service: main
    image: ghcr.io/hotio/prowlarr
    environment:
      TZ: ${DAPPS_TIMEZONE}
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
