include:
  - ../networks.yml
x-environment: &environment
  TZ: ${APPS_TIMEZONE}
services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr
    extends:
      file: ../common.yml
      service: main
    expose:
      - 9696
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=9696"
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
