include:
  - ../networks.yml
x-environment: &environment
  GEMINI_CLI_OAUTH_CLIENT_ID: ${APPS_GOOGLE_OAUTH_CLIENT_ID}
  GEMINI_CLI_OAUTH_CLIENT_SECRET: ${APPS_GOOGLE_CLIENT_SECRET}
  GEMINI_OAUTH_CLIENT_ID: ${APPS_GOOGLE_OAUTH_CLIENT_ID}
  GEMINI_OAUTH_CLIENT_SECRET: ${APPS_GOOGLE_CLIENT_SECRET}
  JWT_SECRET: ${APPS_KEY_HEX_64}
  API_KEY_SECRET: ${APPS_KEY_HEX_32}
  STORAGE_ENCRYPTION_KEY: ${APPS_KEY_HEX_32}
  INITIAL_PASSWORD: ${APPS_ADMIN_DEFAULT_PASS}
  DATA_DIR: /data
  BASE_URL: https://${APP_NAME}.${APPS_DOMAIN}
  NEXT_PUBLIC_BASE_URL: https://${APP_NAME}.${APPS_DOMAIN}
  NODE_ENV: production
services:
  omniroute:
    image: diegosouzapw/omniroute
    extends:
      file: ../common.yml
      service: main
    environment: *environment
    stop_grace_period: 40s
    volumes:
      - ../../apps-data/${APP_NAME}/data:/data
