include:
  - ../networks.yml
x-environment: &environment
  JWT_SECRET: ${DAPPS_KEY_HEX_64}
  API_KEY_SECRET: ${DAPPS_KEY_HEX_32}
  STORAGE_ENCRYPTION_KEY: ${DAPPS_KEY_HEX_32}
  INITIAL_PASSWORD: ${DAPPS_ADMIN_DEFAULT_PASS}
  DATA_DIR: /data
  BASE_URL: https://${APP_NAME}.${DAPPS_DOMAIN}
  NEXT_PUBLIC_BASE_URL: https://${APP_NAME}.${DAPPS_DOMAIN}
  NODE_ENV: production
services:
  omniroute:
    image: diegosouzapw/omniroute
    extends:
      file: ../common.yml
      service: main
    environment: *environment
    stop_grace_period: 40s
    volumes:
      - ../../apps-data/${APP_NAME}/data:/data
