services:
  traefik:
    image: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ../../apps-data/${APP_NAME}/acme.json:/acme.json
    networks:
      - traefik
networks:
  traefik:
    external: true
