include:
  - ../networks.yml
services:
  outline-admin:
    image: amro045/outline-admin
    extends:
      file: ../common.yml
      service: main
    volumes:
      - ../../apps-data/${APP_NAME}/data:/app/data
      - ../../apps-data/${APP_NAME}/logs:/app/logs
