include:
  - ../postgres.yml
services:
  maybe:
    image: ghcr.io/maybe-finance/maybe:latest
    volumes:
      - ../../apps-data/${APP_NAME}/storage:/rails/storage
    expose:
      - ${APP_PORT}
    restart: unless-stopped
    environment:
      SELF_HOSTED: "true"
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      GOOD_JOB_EXECUTION_MODE: async
      SECRET_KEY_BASE:  ${DAPPS_KEY_HEX_64}
      DB_HOST: postgres
      POSTGRES_DB: ${APP_NAME}
      POSTGRES_USER: ${APP_NAME}
      POSTGRES_PASSWORD: ${DAPPS_DATABASE_PASSWORD}
    depends_on:
      - postgres
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${DAPPS_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=${DAPPS_CERTIFICATE_RESOLVER}"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"
networks:
  internal:
  traefik:
    external: true
