include:
  - ../networks.yml
  - ../postgres.yml
  - ../gotenberg.yml
x-image: &image solidtime/solidtime
x-user: &user "${DAPPS_UID}:${DAPPS_GID}"
x-environment: &environment
  APP_NAME: solidtime
  VITE_APP_NAME: solidtime
  APP_ENV: production
  APP_DEBUG: false
  APP_URL: https://${APP_NAME}.${DAPPS_DOMAIN}
  APP_FORCE_HTTPS: true
  TRUSTED_PROXIES: 172.16.0.0/12,10.0.0.0/8
  APP_KEY: ${DAPPS_KEY_BASE64_32}
  LOG_CHANNEL: stderr_daily
  LOG_LEVEL: info
  DB_CONNECTION: pgsql
  DB_HOST: postgres
  DB_PORT: 5432
  DB_SSLMODE: prefer
  DB_DATABASE: ${APP_NAME}
  DB_USERNAME: ${APP_NAME}
  DB_PASSWORD: ${DAPPS_DATABASE_PASSWORD}
  MAIL_MAILER: smtp
  MAIL_HOST: ${DAPPS_SMTP_HOSTNAME}
  MAIL_PORT: ${DAPPS_SMTP_PORT}
  MAIL_ENCRYPTION: tls
  MAIL_FROM_ADDRESS: ${DAPPS_SMTP_FROM}
  MAIL_FROM_NAME: solidtime
  MAIL_USERNAME: ${DAPPS_SMTP_USERNAME}
  MAIL_PASSWORD: ${DAPPS_SMTP_PASSWORD}
  QUEUE_CONNECTION: database
  FILESYSTEM_DISK: local
  PUBLIC_FILESYSTEM_DISK: public
  SUPER_ADMINS: ${DAPPS_ADMIN_MAIL}
  GOTENBERG_URL: http://gotenberg:3000
x-volumes: &volumes
  - ../../apps-data/${APP_NAME}/storage:/var/www/html/storage
  - ../../apps-data/${APP_NAME}/logs:/var/www/html/storage/logs"
  - ../../apps-data/${APP_NAME}/app:/var/www/html/storage/app"
services:
  app:
    image: *image
    extends:
      file: ../common.yml
      service: main
    user: *user
    environment:
      <<: *environment
      CONTAINER_MODE: http
      AUTO_DB_MIGRATE: true
    volumes: *volumes
    depends_on:
      - postgres
      - gotenberg
  scheduler:
    image: *image
    extends:
      file: ../common.yml
      service: side
    user: *user
    environment:
      <<: *environment
      CONTAINER_MODE: scheduler
    volumes: *volumes
    healthcheck:
      test: ["CMD", "healthcheck"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
  queue:
    image: *image
    extends:
      file: ../common.yml
      service: side
    user: *user
    environment:
      <<: *environment
      CONTAINER_MODE: worker
      WORKER_COMMAND: php /var/www/html/artisan queue:work
    volumes: *volumes
    healthcheck:
      test: ["CMD", "healthcheck"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
      - gotenberg
