include:
  - ../networks.yml
x-environment: &environment
  JWT_SECRET: ${APPS_KEY_HEX_64}
  API_KEY_SECRET: ${APPS_KEY_HEX_32}
  MACHINE_ID_SALT: ${APPS_KEY_HEX_32}
  INITIAL_PASSWORD: ${APPS_ADMIN_DEFAULT_PASS}
  DATA_DIR: /data
  HOME: /data
  BASE_URL: https://${APP_NAME}.${APPS_DOMAIN}
  NEXT_PUBLIC_BASE_URL: https://${APP_NAME}.${APPS_DOMAIN}
  NODE_ENV: production
  NEXT_TELEMETRY_DISABLED: 1
services:
  9router:
    image: ghcr.io/decolua/9router
    extends:
      file: ../common.yml
      service: main
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/data:/data
