include:
  - ../networks.yml
services:
  bazarr:
    extends:
      file: ../common.yml
      service: main
    image: ghcr.io/hotio/bazarr
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${DAPPS_TIMEZONE}
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
      - ${JELLYFIN_SHOWS_PATH}:/shows
      - ${JELLYFIN_VIDEO_PATH}:/video
