include:
  - ../networks.yml
services:
  whoami:
    image: traefik/whoami
    extends:
      file: ../common.yml
      service: main
    expose:
      - 80
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
