include:
  - ../networks.yml
  - ../paradedb.yml
  - ../redis.yml
x-environment: &environment
  DATABASE_URL: postgresql://${APP_NAME}:${DAPPS_DATABASE_PASSWORD}@paradedb:5432/${APP_NAME}
  KEY_VAULTS_SECRET: ${DAPPS_KEY_HEX_16}
  AUTH_SECRET: ${DAPPS_KEY_HEX_64}
  APP_URL: https://${APP_NAME}.${DAPPS_DOMAIN}
  INTERNAL_APP_URL: http://localhost:${APP_PORT}
  S3_ENDPOINT: https://${DAPPS_S3_HOST}
  S3_BUCKET: ${APP_NAME}
  S3_REGION: ${DAPPS_S3_REGION}
  S3_ACCESS_KEY_ID: ${DAPPS_S3_ACCESS_KEY_ID}
  S3_SECRET_ACCESS_KEY: ${DAPPS_S3_SECRET_ACCESS_KEY}
  S3_ENABLE_PATH_STYLE: 1
  S3_SET_ACL: 0
  LLM_VISION_IMAGE_USE_BASE64: 1
  REDIS_URL: redis://redis:6379
  REDIS_PREFIX: lobehub
  REDIS_TLS: 0
  ENABLE_OIDC: 1
  JWKS_KEY: ${LOBEHUB_JWKS_KEY}
  NODE_ENV: production
services:
  lobehub:
    image: lobehub/lobehub
    extends:
      file: ../common.yml
      service: main
    environment: *environment
    depends_on:
      - paradedb
      - redis
