include:
  - ../networks.yml
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    expose:
      - ${APP_PORT}
    volumes:
      - ../../apps-data/${APP_NAME}/data:/app/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${DAPPS_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=${DAPPS_CERTIFICATE_RESOLVER}"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"
