services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    expose:
      - 3001
    volumes:
      - ../../apps-data/${APP_NAME}/data:/app/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${DAPPS_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=acmeHttpChallengeResolver"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=3001"
networks:
  traefik:
    external: true
