include:
  - ../networks.yml
services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    extends:
      file: ../common.yml
      service: main
    volumes:
      - ../../apps-data/${APP_NAME}/data:/app/data
