include:
  - ../networks.yml
  - ../postgres.yml
  - ../redis.yml
services:
  worker:
    image: ghcr.io/we-promise/sure:latest
    extends:
      file: ../common.yml
      service: side
    volumes:
      - ../../apps-data/${APP_NAME}/storage:/rails/storage
    command: bundle exec sidekiq
    environment:
      SELF_HOSTED: "true"
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      SECRET_KEY_BASE:  ${DAPPS_KEY_HEX_64}
      DB_HOST: postgres
      POSTGRES_DB: ${APP_NAME}
      POSTGRES_USER: ${APP_NAME}
      POSTGRES_PASSWORD: ${DAPPS_DATABASE_PASSWORD}
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "ps", "aux | grep '[s]idekiq'"]
  web:
    image: ghcr.io/we-promise/sure:latest
    extends:
      file: ../common.yml
      service: main
    volumes:
      - ../../apps-data/${APP_NAME}/storage:/rails/storage
    environment:
      SELF_HOSTED: "true"
      RAILS_FORCE_SSL: "false"
      RAILS_ASSUME_SSL: "false"
      SECRET_KEY_BASE:  ${DAPPS_KEY_HEX_64}
      DB_HOST: postgres
      POSTGRES_DB: ${APP_NAME}
      POSTGRES_USER: ${APP_NAME}
      POSTGRES_PASSWORD: ${DAPPS_DATABASE_PASSWORD}
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - postgres
      - redis
