services:
  qbittorrent:
    image: linuxserver/qbittorrent
    dns:
      - 8.8.8.8
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${DAPPS_TIMEZONE}
      - WEBUI_PORT=8133
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
      - ../../apps-data/${APP_NAME}/media/torrents:/media/torrents
    network_mode: "host"
    ports:
      - "8133:8133"
    restart: unless-stopped
