include:
  - ../networks.yml
x-environment: &environment
  PUID: ${DAPPS_UID}
  PGID: ${DAPPS_GID}
  TZ: ${DAPPS_TIMEZONE}
  WEBUI_PORT: ${APP_PORT}
services:
  qbittorrent:
    extends:
      file: ../common.yml
      service: main
    image: linuxserver/qbittorrent
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
      - ../../apps-data/${APP_NAME}/downloads:/downloads
