services:
  beszel-agent:
    image: 'henrygd/beszel-agent'
    extends:
      file: ../common.yml
      service: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      PORT: ${APP_PORT}
      KEY: ${BESZEL_AGENT_PUBLIC_KEY}
