x-environment: &environment
  PORT: ${APP_PORT}
  KEY: ${BESZEL_AGENT_PUBLIC_KEY}
services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    extends:
      file: ../common.yml
      service: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home:/extra-filesystems/home:ro
    environment: *environment
    cap_add:
        - SYS_RAWIO # required for S.M.A.R.T. data
        - SYS_ADMIN # required for NVMe S.M.A.R.T. data
    devices:
      - /dev/sda:/dev/sda
      - /dev/nvme0:/dev/nvme0
    healthcheck:
      test: ["CMD", "/agent", "health"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
