include:
  - ../networks.yml
x-environment: &environment
  - PUID=1000
  - PGID=1000
  - APP_KEY=${DAPPS_KEY_HEX_16}
  - DB_CONNECTION=sqlite
  - SPEEDTEST_SCHEDULE='*/10 * * * *'
  - SPEEDTEST_SERVERS='60747'
services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker
    extends:
      file: ../common.yml
      service: main
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
