services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    environment:
      - COLLECTOR_CRON_SCHEDULE='0 */1 * * *'
    ports:
      - "8080:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ./data:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/nvme0"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.${DOMAIN}`)"
      - "traefik.http.routers.${NAME}.tls.certresolver=acmeHttpChallengeResolver"
    networks:
      - traefik
networks:
  traefik:
    external: true
