include:
  - ../postgres.yml
services:
  app:
    image: monica
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - APP_KEY=${DAPPS_KEY_HEX_32}
      - APP_ENV=production
      - DB_CONNECTION=pgsql
      - DB_DATABASE=${APP_NAME}
      - DB_HOST=postgres
      - DB_USERNAME=${APP_NAME}
      - DB_PASSWORD=${DAPPS_DATABASE_PASSWORD}
    expose:
      - 80
    volumes:
      - ../../apps-data/${APP_NAME}/storage:/var/www/html/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${DAPPS_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=acmeHttpChallengeResolver"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
    networks:
      - internal
      - traefik
networks:
  internal:
  traefik:
    external: true
