include:
  - ../networks.yml
  - ../mysql-8.yml
x-environment: &environment
  APP_KEY: ${APPS_KEY_BASE64_32}
  APP_ENV: production
  DB_DATABASE: ${APP_NAME}
  DB_HOST: mysql
  DB_USERNAME: ${APP_NAME}
  DB_PASSWORD: ${APPS_DATABASE_PASSWORD}
services:
  app:
    image: monica
    extends:
      file: ../common.yml
      service: main
    expose:
      - 80
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/storage:/var/www/html/storage
    depends_on:
      - mysql
