include:
  - ../networks.yml
services:
  portainer:
    image: portainer/portainer-ce
    extends:
      file: ../common.yml
      service: main
    expose:
      - 9000
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../apps-data/${APP_NAME}/data:/data
    security_opt:
      - no-new-privileges:true
