services:
  portainer:
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - 9000
      - 9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../apps-data/${APP_NAME}/data:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${DAPPS_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=acmeHttpChallengeResolver"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=9000"
networks:
  traefik:
    external: true
