include:
  - ../networks.yml
services:
  portainer:
    extends:
      file: ../common.yml
      service: main
    image: portainer/portainer-ce
    command: -H unix:///var/run/docker.sock
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../apps-data/${APP_NAME}/data:/data
