include:
  - ../networks.yml
  - ../postgres-17.yml
x-environment: &environment
  TZ: ${APPS_TIMEZONE}
  DB_TYPE: postgres
  DB_HOST: postgres
  DB_PORT: ${APP_NAME}
  DB_USER: ${APP_NAME}
  DB_PASS: ${APPS_DATABASE_PASSWORD}
  DB_NAME: ${APP_NAME}
  DB_LOG_QUERIES: false
  DB_USE_SSL: false
services:
  jellyseerr:
    extends:
      file: ../common.yml
      service: main
    image: fallenbagel/jellyseerr
    depends_on:
      - postgres
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 30s
      timeout: 5s
      interval: 30s
      retries: 5
