services:
  beszel:
    image: 'henrygd/beszel'
    restart: unless-stopped
    expose:
      - 8090
    volumes:
      - ../../apps-data/${APP_NAME}/beszel_data:/beszel_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${DAPPS_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=${DAPPS_CERTIFICATE_RESOLVER}"
    networks:
      - traefik
networks:
  traefik:
    external: true
