include:
  - ../networks.yml
services:
  beszel:
    image: 'henrygd/beszel'
    extends:
      file: ../common.yml
      service: main
    volumes:
      - ../../apps-data/${APP_NAME}/beszel_data:/beszel_data
