services:
  home-assistant:
    image: "homeassistant/home-assistant"
    extends:
      file: ../common.yml
      service: host
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    privileged: true

