include:
  - ../networks.yml
x-environment: &environment
  TZ: ${DAPPS_TIMEZONE}
services:
  audiobookshelf:
    extends:
      file: ../common.yml
      service: main
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/config:/config
      - ../../apps-data/${APP_NAME}/podcasts:/podcasts
      - ../../apps-data/${APP_NAME}/metadata:/metadata
      - ${AUDIOBOOKSHELF_AUDIOBOOKS_PATH}:/audiobooks
