include:
  - ../networks.yml
x-environment: &environment
  TZ: ${APPS_TIMEZONE}
services:
  glance:
    image: glanceapp/glance
    extends:
      file: ../common.yml
      service: main
    expose:
      - 8080
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=8080"
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/config:/app/config
      - ../../apps-data/${APP_NAME}/config/assets:/app/assets
