services:
  portainer:
    image: portainer/portainer-ce:2.18.4-alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - 9000
      - 9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/:/data/
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.`${NAME}`.rule=Host(`${NAME}.${DOMAIN}`)"
      - "traefik.http.routers.`${NAME}`.tls.certresolver=acmeHttpChallengeResolver"
      - "traefik.http.services.`${NAME}`.loadbalancer.server.port=9000"
networks:
  traefik:
    external: true
