services:
  beszel:
    image: 'henrygd/beszel'
    container_name: ${NAME}
    restart: unless-stopped
    ports:
      - '8090:8090'
    volumes:
      - ./data:/beszel_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.${DOMAIN}`)"
      - "traefik.http.routers.${NAME}.tls.certresolver=acmeHttpChallengeResolver"
    networks:
      - traefik
networks:
  traefik:
    external: true
