include:
  - ../networks.yml
  - ../postgres.yml
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    expose:
      - ${APP_PORT}
    environment:
      DATABASE_URL: postgresql://${APP_NAME}:${DAPPS_DATABASE_PASSWORD}@postgres:5432/${APP_NAME}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${DAPPS_KEY_HEX_32}
    depends_on:
      - postgres
    init: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:${APP_PORT}/api/heartbeat"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${DAPPS_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=${DAPPS_CERTIFICATE_RESOLVER}"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"
