include:
  - ../postgres.yml
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    expose:
      - 3000
    environment:
      DATABASE_URL: postgresql://${APP_NAME}:${DAPPS_POSTGRES_PASSWORD}@postgres:5432/${APP_NAME}
      DATABASE_TYPE: postgresql
      APP_SECRET: ${DAPPS_KEY_HEX_32}
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${DAPPS_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=acmeHttpChallengeResolver"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=3000"
networks:
  internal:
  traefik:
    external: true
