# https://docs.growthbook.io/self-host/env
include:
  - ../networks.yml
  - ../mongodb.yml
x-environment: &environment
  MONGODB_URI: mongodb://root:${DAPPS_DATABASE_PASSWORD}@mongo:27017/${APP_NAME}?authSource=admin
  NODE_ENV: production
  ENCRYPTION_KEY: DAPPS_KEY_HEX_16
  JWT_SECRET: DAPPS_KEY_HEX_32
  APP_ORIGIN: https://${APP_NAME}.${DAPPS_DOMAIN}
  API_HOST: https://${APP_NAME}.${DAPPS_DOMAIN}/backend-api
services:
  growthbook:
    image: growthbook/growthbook
    extends:
      file: ../common.yml
      service: main
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/uploads:/usr/local/src/app/packages/back-end/uploads
    depends_on:
      - mongo
    labels:
      - traefik.http.routers.${APP_NAME}-backend-api.rule=Host(`${APP_NAME}.${DAPPS_DOMAIN}`) && PathPrefix(`/backend-api`)
      - traefik.http.routers.${APP_NAME}-backend-api.tls.certresolver=${DAPPS_CERTIFICATE_RESOLVER}
      - traefik.http.middlewares.${APP_NAME}-backend-api-strip.stripprefix.prefixes=/backend-api
      - traefik.http.routers.${APP_NAME}-backend-api.middlewares=${APP_NAME}-backend-api-strip
      - traefik.http.services.${APP_NAME}-backend-api.loadbalancer.server.port=3100
