include:
  - ../networks.yml
x-environment: &environment
  TZ: ${APPS_TIMEZONE}
services:
  wallos:
    image: bellamy/wallos
    extends:
      file: ../common.yml
      service: main
    expose:
      - 80
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/db:/var/www/html/db
      - ../../apps-data/${APP_NAME}/logos:/var/www/html/images/uploads/logos
