services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./data:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${NAME}.rule=Host(`${NAME}.${DOMAIN}`)"
      - "traefik.http.routers.${NAME}.tls.certresolver=acmeHttpChallengeResolver"
      - "traefik.http.services.${NAME}.loadbalancer.server.port=8081"
    networks:
      - traefik
networks:
  internal:
  traefik:
    external: true
