include:
  - ../networks.yml
  - ../postgres.yml
  - ../redis.yml
x-environment: &environment
  NODE_ENV: production
  NEXT_PUBLIC_SELF_HOSTED: true
  BATCH_SIZE: 5000
  BATCH_INTERVAL: 10000
  ALLOW_REGISTRATION: false
  ALLOW_INVITATION: true
  REDIS_URL: redis://redis:6379
  CLICKHOUSE_URL: http://clickhouse:8123/${APP_NAME}
  DATABASE_URL: postgresql://${APP_NAME}:${DAPPS_DATABASE_PASSWORD}@postgres:5432/${APP_NAME}
  DATABASE_URL_DIRECT: postgresql://${APP_NAME}:${DAPPS_DATABASE_PASSWORD}@postgres:5432/${APP_NAME}
  NEXT_PUBLIC_DASHBOARD_URL: https://${APP_NAME}.${DAPPS_DOMAIN}
  NEXT_PUBLIC_API_URL: https://${APP_NAME}.${DAPPS_DOMAIN}/api
  COOKIE_SECRET: ${DAPPS_KEY_HEX_64}
services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3.2-alpine
    extends:
      file: ../common.yml
      service: side
    volumes:
      - ../../apps-data/${APP_NAME}/clickhouse/data:/var/lib/clickhouse
      - ../../apps-data/${APP_NAME}/clickhouse/logs:/var/log/clickhouse-server
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/op-config.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/op-user-config.xml:ro
      - ./clickhouse/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  openpanel-api:
    image: lindesvard/openpanel-api
    extends:
      file: ../common.yml
      service: side
    command:
      [
        "sh",
        "-c",
        "echo 'Running migrations...' && CI=true pnpm -r run migrate:deploy && pnpm start",
      ]
    environment: *environment
    depends_on:
      - postgres
      - redis
      - clickhouse
  openpanel-dashboard:
    image: lindesvard/openpanel-dashboard
    extends:
      file: ../common.yml
      service: main
    environment: *environment
    depends_on:
      - postgres
      - redis
      - openpanel-api
  openpanel-worker:
    image: lindesvard/openpanel-worker
    extends:
      file: ../common.yml
      service: side
    environment: *environment
    depends_on:
      - postgres
      - redis
      - openpanel-api
