include:
  - ../networks.yml
  - ../postgres.yml
  - ../redis.yml
  - ../clickhouse.yml
x-environment: &environment
  NODE_ENV: production
  VITE_SELF_HOSTED: true
  BATCH_SIZE: 5000
  BATCH_INTERVAL: 10000
  ALLOW_REGISTRATION: false
  ALLOW_INVITATION: true
  REDIS_URL: redis://redis:6379
  CLICKHOUSE_URL: http://clickhouse:8123
  DATABASE_URL: postgresql://postgres:${DAPPS_DATABASE_PASSWORD}@postgres:5432/${APP_NAME}
  DATABASE_URL_DIRECT: postgresql://postgres:${DAPPS_DATABASE_PASSWORD}@postgres:5432/${APP_NAME}
  DASHBOARD_URL: https://${APP_NAME}.${DAPPS_DOMAIN}
  API_URL: https://${APP_NAME}.${DAPPS_DOMAIN}/api
  COOKIE_SECRET: ${DAPPS_KEY_HEX_64}
  EMAIL_SENDER: ${DAPPS_SMTP_FROM}
  RESEND_API_KEY: ${DAPPS_SMTP_PASSWORD}
services:
  openpanel-api:
    image: lindesvard/openpanel-api
    extends:
      file: ../common.yml
      service: side
    command:
      ["sh", "-c", "echo 'Running migrations...' && CI=true pnpm -r run migrate:deploy && pnpm start"]
    environment: *environment
    depends_on:
      - postgres
      - redis
      - clickhouse
  openpanel-dashboard:
    image: lindesvard/openpanel-dashboard
    extends:
      file: ../common.yml
      service: main
    environment: *environment
    depends_on:
      - postgres
      - redis
      - openpanel-api
  openpanel-worker:
    image: lindesvard/openpanel-worker
    extends:
      file: ../common.yml
      service: side
    environment: *environment
    depends_on:
      - postgres
      - redis
      - openpanel-api
