include:
  - ../networks.yml
x-environment: &environment
  TZ: ${APPS_TIMEZONE}
services:
  playwright:
    image: mcr.microsoft.com/playwright/mcp
    extends:
      file: ../common.yml
      service: side
    command: ["--port", "8931", "--host", "0.0.0.0"]
    environment: *environment
    networks:
      internal:
      mcp:
        aliases:
          - playwright
    init: true
