services:
  homer:
    image: b4bz/homer
    restart: unless-stopped
    volumes:
      - ./../apps-data/${APP_NAME}/assets:/www/assets
    expose:
      - ${APP_PORT}
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${DAPPS_DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.tls.certresolver=${DAPPS_CERTIFICATE_RESOLVER}"
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"
      - "traefik.http.routers.${APP_NAME}.middlewares=${APP_NAME}-auth-basic"
      - "traefik.http.middlewares.${APP_NAME}-auth-basic.basicauth.users=${DAPPS_HTPASSWD}"
networks:
  traefik:
    external: true
