include:
  - ../networks.yml
x-environment: &environment
  WG_HOST: ${DAPPS_HOST}
  LANGUAGE: en
  PORT: 80
  PASSWORD_HASH: ${WG_EASY_PASSWORD_HASH}
  WG_PORT: 51821
  WG_DEFAULT_ADDRESS: "10.36.0.x"
  WG_DEFAULT_DNS: "1.1.1.1"
  WG_ALLOWED_IPS: "0.0.0.0/0, ::/0"
  WG_PERSISTENT_KEEPALIVE: 20
  WG_MTU: 1420
  USE_GRAVATAR: true
services:
  amnezia-wg-easy:
    extends:
      file: ../common.yml
      service: main
    image: ghcr.io/w0rng/amnezia-wg-easy
    volumes:
      - ../../apps-data/${APP_NAME}/wireguard:/etc/wireguard
    environment: *environment
    ports:
      - "51821:51821/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    devices:
      - /dev/net/tun:/dev/net/tun
