include:
  - ../networks.yml
x-environment: &environment
  TZ: ${DAPPS_TIMEZONE}
  CRON_MIN: "3,17,32,47"
  TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16
  PICCACHE_ACCESS_TOKEN: ${DAPPS_ADMIN_DEFAULT_PASS}
  PICCACHE_CACHE_PATH: /var/www/FreshRSS/data
services:
  freshrss-db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: freshrss
      POSTGRES_USER: freshrss
      POSTGRES_PASSWORD: ${FRESHRSS_DB_PASSWORD}
    volumes:
      - ../../apps-data/${APP_NAME}/db:/var/lib/postgresql/data
    networks:
      - internal
    logging:
      options:
        max-size: 10m

  freshrss:
    image: freshrss/freshrss
    extends:
      file: ../common.yml
      service: main
    environment:
      <<: *environment
      DB_HOST: freshrss-db
      DB_BASE: freshrss
      DB_USER: freshrss
      DB_PASSWORD: ${FRESHRSS_DB_PASSWORD}
    depends_on:
      - freshrss-db
    volumes:
      - ../../apps-data/${APP_NAME}/data:/var/www/FreshRSS/data
      - ../../apps-data/${APP_NAME}/extensions:/var/www/FreshRSS/extensions
      - ./piccache.php:/var/www/FreshRSS/p/piccache.php
