include:
  - ../networks.yml
x-environment: &environment
  TZ: ${DAPPS_TIMEZONE}
  CRON_MIN: "3,33"
  TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16
services:
  freshrss:
    image: freshrss/freshrss
    extends:
      file: ../common.yml
      service: main
    environment: *environment
    volumes:
      - ../../apps-data/${APP_NAME}/data:/var/www/FreshRSS/data
      - ../../apps-data/${APP_NAME}/extensions:/var/www/FreshRSS/extensions
    logging:
      options:
        max-size: 10m
