name: CD
on:
  push:
    branches: ["main"]
concurrency:
  group: ci-deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Setup Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          tags: tag:ci
          use-cache: "true"
      - name: Create .env
        uses: SpicyPizza/create-envfile@v2
        with:
          envkey_APPS_ADMIN_MAIL: ${{ vars.DAPPS_ADMIN_MAIL }}
          envkey_APPS_ADMIN_DEFAULT_PASS: ${{ secrets.DAPPS_ADMIN_DEFAULT_PASS }}
          envkey_APPS_CERTIFICATE_RESOLVER: ${{ vars.DAPPS_CERTIFICATE_RESOLVER }}
          envkey_APPS_CLOUDFLARE_DNS_API_TOKEN: ${{ secrets.DAPPS_CLOUDFLARE_DNS_API_TOKEN }}
          envkey_APPS_TIMEZONE: ${{ vars.DAPPS_TIMEZONE }}
          envkey_APPS_DATABASE_PASSWORD: ${{ secrets.DAPPS_DATABASE_PASSWORD }}
          envkey_APPS_KEY_HEX_16: ${{ secrets.DAPPS_KEY_HEX_16 }}
          envkey_APPS_KEY_HEX_32: ${{ secrets.DAPPS_KEY_HEX_32 }}
          envkey_APPS_KEY_HEX_64: ${{ secrets.DAPPS_KEY_HEX_64 }}
          envkey_APPS_KEY_BASE64_32: ${{ secrets.DAPPS_KEY_BASE64_32 }}
          envkey_APPS_TELEGRAM_TELEGRAM_TOKEN: ${{ secrets.DAPPS_TELEGRAM_TELEGRAM_TOKEN }}
          envkey_APPS_TELEGRAM_CHAT: ${{ vars.DAPPS_TELEGRAM_CHAT }}
          envkey_APPS_SHOUTRRR_TELEGRAM_NOTIFICATION_URL: ${{ secrets.DAPPS_SHOUTRRR_TELEGRAM_NOTIFICATION_URL }}
          envkey_APPS_HTPASSWD: ${{ secrets.DAPPS_HTPASSWD }}
          envkey_APPS_SMTP_HOSTNAME: ${{ vars.DAPPS_SMTP_HOSTNAME }}
          envkey_APPS_SMTP_PORT: ${{ vars.DAPPS_SMTP_PORT }}
          envkey_APPS_SMTP_USERNAME: ${{ vars.DAPPS_SMTP_USERNAME }}
          envkey_APPS_SMTP_PASSWORD: ${{ secrets.DAPPS_SMTP_PASSWORD }}
          envkey_APPS_SMTP_FROM: ${{ vars.DAPPS_SMTP_FROM }}
          envkey_APPS_S3_HOST: ${{ vars.DAPPS_S3_HOST }}
          envkey_APPS_S3_REGION: ${{ vars.DAPPS_S3_REGION }}
          envkey_APPS_S3_ACCESS_KEY_ID: ${{ vars.DAPPS_S3_ACCESS_KEY_ID }}
          envkey_APPS_S3_SECRET_ACCESS_KEY: ${{ secrets.DAPPS_S3_SECRET_ACCESS_KEY }}
          envkey_BESZEL_AGENT_PUBLIC_KEY: ${{ vars.BESZEL_AGENT_PUBLIC_KEY }}
          envkey_RSSHUB_ACCESS_KEY: ${{ secrets.RSSHUB_ACCESS_KEY }}
          envkey_RSSHUB_TWITTER_AUTH_TOKEN: ${{ secrets.RSSHUB_TWITTER_AUTH_TOKEN }}
          envkey_RSSHUB_YOUTUBE_KEY: ${{ secrets.RSSHUB_YOUTUBE_KEY }}
          envkey_ICLOUDPD_USERNAME: ${{ vars.ICLOUDPD_USERNAME }}
          envkey_ICLOUDPD_PASSWORD: ${{ secrets.ICLOUDPD_PASSWORD }}
          envkey_ICLOUDPD_ALBUM: ${{ vars.ICLOUDPD_ALBUM }}
          envkey_CODECOV_GITHUB_CLIENT_ID: ${{ vars.CODECOV_GITHUB_CLIENT_ID }}
          envkey_CODECOV_GITHUB_CLIENT_SECRET: ${{ secrets.CODECOV_GITHUB_CLIENT_SECRET }}
          envkey_CODECOV_GITHUB_WEBHOOK_SECRET: ${{ secrets.CODECOV_GITHUB_WEBHOOK_SECRET }}
          envkey_CODECOV_GITHUB_APP_ID: ${{ vars.CODECOV_GITHUB_APP_ID }}
          envkey_CODECOV_ADMIN_GITHUB_USERNAME: ${{ vars.CODECOV_ADMIN_GITHUB_USERNAME }}
          envkey_CODECOV_LICENSE: ${{ secrets.CODECOV_LICENSE }}
          envkey_CODECOV_S3_BUCKET: ${{ vars.CODECOV_S3_BUCKET }}
          envkey_JELLYFIN_SHOWS_PATH: ${{ vars.JELLYFIN_SHOWS_PATH }}
          envkey_JELLYFIN_VIDEO_PATH: ${{ vars.JELLYFIN_VIDEO_PATH }}
          envkey_STASH_VIDEO_PATH: ${{ vars.STASH_VIDEO_PATH }}
          envkey_WG_EASY_PASSWORD_HASH: ${{ secrets.WG_EASY_PASSWORD_HASH }}
          envkey_ICLOUDPD_DATA_PATH: ${{ vars.ICLOUDPD_DATA_PATH }}
          envkey_AUDIOBOOKSHELF_AUDIOBOOKS_PATH: ${{ vars.AUDIOBOOKSHELF_AUDIOBOOKS_PATH }}
          envkey_METUBE_DOWNLOADS_PATH: ${{ vars.METUBE_DOWNLOADS_PATH }}
          envkey_APPS_UID: ${{ vars.DAPPS_UID }}
          envkey_APPS_GID: ${{ vars.DAPPS_GID }}
          envkey_YAMTRACK_TRAKT_CLIENT_ID: ${{ vars.YAMTRACK_TRAKT_CLIENT_ID }}
          envkey_YAMTRACK_TRAKT_CLIENT_SECRET: ${{ secrets.YAMTRACK_TRAKT_CLIENT_SECRET }}
          envkey_APPS_GOOGLE_OAUTH_CLIENT_ID: ${{ vars.DAPPS_GOOGLE_OAUTH_CLIENT_ID }}
          envkey_APPS_GOOGLE_CLIENT_SECRET: ${{ secrets.DAPPS_GOOGLE_CLIENT_SECRET }}
          file_name: .env
      - name: Upload .env via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: root
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          source: ".env"
          target: ${{ vars.DEPLOY_PATH }}
      - name: Git pull deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: root
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          envs: GITHUB_TOKEN
          script: |
            cd ${{ vars.DEPLOY_PATH }}

            git fetch https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git ${{ github.ref_name }}
            git reset --hard FETCH_HEAD
            ./restart.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: rubycats-com/jarvis-report-action@main
        if: success() || failure()
        with:
          report-to: ${{ vars.DAPPS_TELEGRAM_CHAT }}
          token: ${{ secrets.DAPPS_TELEGRAM_TELEGRAM_TOKEN }}
