name: Lint
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dupmachine/baseline/.github/actions/lint-yamllint@latest
      - uses: dupmachine/baseline/.github/actions/lint-pymarkdown@latest
      - uses: dupmachine/baseline/.github/actions/lint-ruff@latest
      - uses: dupmachine/baseline/.github/actions/lint-shellcheck@latest
      - uses: dupmachine/baseline/.github/actions/lint-actionlint@latest
