name: Lint
on:
  push:
    branches: ["main"]
  pull_request:
jobs:
  yamllint:
    uses: dupmachine/baseline/.github/workflows/yamllint.yml@main
  pymarkdown:
    uses: dupmachine/baseline/.github/workflows/pymarkdown.yml@main
  ruff:
    uses: dupmachine/baseline/.github/workflows/ruff.yml@main
  shellcheck:
    uses: dupmachine/baseline/.github/workflows/shellcheck.yml@main
  actionlint:
    uses: dupmachine/baseline/.github/workflows/actionlint.yml@main
