include:
  - ../networks.yml
  - ../pgvector.yml
  - ../redis.yml
x-environment: &environment
  environment:
    # https://www.chatwoot.com/docs/self-hosted/configuration/environment-variables/#rails-production-variables
    SECRET_KEY_BASE: ${DAPPS_KEY_HEX_64} # Replace it with the URL you are planning to use for your app
    FRONTEND_URL: https://${APP_NAME}.${DAPPS_DOMAIN} # To use a dedicated URL for help center pages
    # HELPCENTER_URL=http://0.0.0.0:3000 # If the variable is set, all non-authenticated pages would fall back to the default locale.
    # DEFAULT_LOCALE=en # Whenever a new account is created, the default language will be DEFAULT_LOCALE instead of en
    ENABLE_ACCOUNT_SIGNUP: false # true: default option, allows signups, false: disable, api_only: disables the UI, but you can use account apis
    REDIS_URL: redis://redis:6379/ # You can also use the following format for the URL: redis://:password@host:port/db_number
    INSTALLATION_ENV: docker
    POSTGRES_DB: ${APP_NAME}
    POSTGRES_DATABASE: ${APP_NAME}
    POSTGRES_USER: ${APP_NAME}
    POSTGRES_USERNAME: ${APP_NAME}
    POSTGRES_HOST: pgvector
    POSTGRES_PASSWORD: ${DAPPS_DATABASE_PASSWORD}
    MAILER_SENDER_EMAIL: Chatwoot <accounts@chatwoot.com> # Email from all outgoing emails are sent: `email@yourdomain.com` or `BrandName <email@yourdomain.com>`
    SMTP_DOMAIN: chatwoot.com
    SMTP_ADDRESS:
    SMTP_PORT: 1025
    SMTP_USERNAME:
    SMTP_PASSWORD:
    SMTP_AUTHENTICATION: # plain,login,cram_md5
    SMTP_ENABLE_STARTTLS_AUTO: true
    SMTP_OPENSSL_VERIFY_MODE: peer # Can be: 'none', 'peer', 'client_once', 'fail_if_no_peer_cert', see http://api.rubyonrails.org/classes/ActionMailer/Base.html
    ## Mail Incoming
    MAILER_INBOUND_EMAIL_DOMAIN: # This is the domain set for the reply emails when conversation continuity is enabled
    # Set this to the appropriate ingress channel with regards to incoming emails
    # Possible values are:
    # relay for Exim, Postfix, Qmail
    # mailgun for Mailgun
    # mandrill for Mandrill
    # postmark for Postmark
    # sendgrid for Sendgrid
    RAILS_INBOUND_EMAIL_SERVICE:
    # Use one of the following based on the email ingress service
    # Ref: https://edgeguides.rubyonrails.org/action_mailbox_basics.html
    # Set this to a password of your choice and use it in the Inbound webhook
    RAILS_INBOUND_EMAIL_PASSWORD:
    # Key
    MAILGUN_INGRESS_SIGNING_KEY:
    MANDRILL_INGRESS_API_KEY:
    # Creating Your Inbound Webhook Instructions for Postmark and Sendgrid:
    # Inbound webhook URL format:
    #    https://actionmailbox:[YOUR_RAILS_INBOUND_EMAIL_PASSWORD]@[YOUR_CHATWOOT_DOMAIN.COM]/rails/action_mailbox/[RAILS_INBOUND_EMAIL_SERVICE]/inbound_emails
    # Note: Replace the values inside the brackets; do not include the brackets themselves.
    # Example: https://actionmailbox:mYRandomPassword3@chatwoot.example.com/rails/action_mailbox/postmark/inbound_emails
    # For Postmark
    # Ensure the 'Include raw email content in JSON payload' checkbox is selected in the inbound webhook section.
    # Storage
    ACTIVE_STORAGE_SERVICE: local
    # Amazon S3
    # documentation: https://www.chatwoot.com/docs/configuring-s3-bucket-as-cloud-storage
    S3_BUCKET_NAME:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_REGION:
    #LOGRAGE_ENABLED=true # Configure this environment variable if you want to use lograge instead of rails logger
    ### This environment variables are only required if you are setting up social media channels
    # https://www.chatwoot.com/docs/facebook-setup
    FB_VERIFY_TOKEN:
    FB_APP_SECRET:
    FB_APP_ID:
    # https://developers.facebook.com/docs/messenger-platform/instagram/get-started#app-dashboard
    IG_VERIFY_TOKEN:
    # https://www.chatwoot.com/docs/twitter-app-setup
    TWITTER_APP_ID:
    TWITTER_CONSUMER_KEY:
    TWITTER_CONSUMER_SECRET:
    TWITTER_ENVIRONMENT:
    # Slack integration
    SLACK_CLIENT_ID:
    SLACK_CLIENT_SECRET:
    # Google OAuth
    GOOGLE_OAUTH_CLIENT_ID:
    GOOGLE_OAUTH_CLIENT_SECRET:
    GOOGLE_OAUTH_CALLBACK_URL:
services:
  rails:
    extends:
      file: ../common.yml
      service: main
    <<: *environment
    image: chatwoot/chatwoot:latest
    depends_on:
      - pgvector
      - redis
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    volumes:
      - ../../apps-data/${APP_NAME}/storage:/app/storage
  sidekiq:
    extends:
      file: ../common.yml
      service: side
    <<: *environment
    image: chatwoot/chatwoot:latest
    depends_on:
      - pgvector
      - redis
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    volumes:
      - ../../apps-data/${APP_NAME}/storage:/app/storage
