include:
  - ../networks.yml
  - ../postgres.yml
  - ../redis.yml
services:
  yamtrack:
    image: ghcr.io/fuzzygrim/yamtrack
    extends:
      file: ../common.yml
      service: main
    depends_on:
      - postgres
      - redis
    environment:
      - ADMIN_ENABLED=True
      - URLS=https://${APP_NAME}.${DAPPS_DOMAIN}
      - TZ=${DAPPS_TIMEZONE}
      - SECRET=${DAPPS_KEY_HEX_64}
      - REDIS_URL=redis://redis:6379
      - DB_HOST=postgres
      - DB_NAME=${APP_NAME}
      - DB_USER=${APP_NAME}
      - DB_PASSWORD=${DAPPS_DATABASE_PASSWORD}
      - DB_PORT=5432
