include:
  - ../networks.yml
  - ../postgres-17.yml
  - ../redis-7.yml
x-environment: &environment
  REGISTRATION: false
  URLS: https://${APP_NAME}.${DAPPS_DOMAIN}
  TZ: ${DAPPS_TIMEZONE}
  SECRET: ${DAPPS_KEY_HEX_64}
  REDIS_URL: redis://redis:6379
  DB_HOST: postgres
  DB_NAME: ${APP_NAME}
  DB_USER: ${APP_NAME}
  DB_PASSWORD: ${DAPPS_DATABASE_PASSWORD}
  DB_PORT: 5432
  TRAKT_API: ${YAMTRACK_TRAKT_CLIENT_ID}
  TRAKT_API_SECRET: ${YAMTRACK_TRAKT_CLIENT_SECRET}
services:
  yamtrack:
    image: ghcr.io/fuzzygrim/yamtrack
    extends:
      file: ../common.yml
      service: main
    environment: *environment
    depends_on:
      - postgres
      - redis
