include:
  - ../networks.yml
  - ../postgres-17.yml
  - ../redis-7.yml
x-environment: &environment
  REGISTRATION: false
  URLS: https://${APP_NAME}.${APPS_DOMAIN}
  TZ: ${APPS_TIMEZONE}
  SECRET: ${APPS_KEY_HEX_64}
  REDIS_URL: redis://redis:6379
  DB_HOST: postgres
  DB_NAME: ${APP_NAME}
  DB_USER: ${APP_NAME}
  DB_PASSWORD: ${APPS_DATABASE_PASSWORD}
  DB_PORT: 5432
  TRAKT_API: ${YAMTRACK_TRAKT_CLIENT_ID}
  TRAKT_API_SECRET: ${YAMTRACK_TRAKT_CLIENT_SECRET}
services:
  yamtrack:
    image: ghcr.io/fuzzygrim/yamtrack
    extends:
      file: ../common.yml
      service: main
    expose:
      - 8000
    labels:
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=8000"
    environment: *environment
    depends_on:
      - postgres
      - redis
